// build.gradle in TeamCode

// Sloth Load plugin
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://repo.dairy.foundation/releases" }
    }
    dependencies {
        classpath "dev.frozenmilk:Load:0.2.4"
    }
}

apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'
apply plugin: 'dev.frozenmilk.sinister.sloth.load'

android {
    namespace = 'org.firstinspires.ftc.teamcode'
    compileSdkVersion 34

    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

repositories {
    maven { url = "https://repo.dairy.foundation/releases" }
}

dependencies {
    implementation project(':FtcRobotController')
    implementation("dev.frozenmilk.sinister:Sloth:0.2.4")
}